### ISSUE TITLE
installation failed on fedora 26

### ISSUE THREAD

**Issue by ghost** [vrutkovs/flatpak-signal#2]
when trying to install on fedora 26 it show that error message 

> The required runtime org.freedesktop.Platform/x86_64/1.6 was not found in a configured remote.

**Comment by vrutkovs** [comment]
Oh, weird, I expected it to install flathub repo.

Do you have any other repos configured? Is there a flathub repo already installed?

**Comment by ghost** [comment]
ooh i solved it by adding the gnome runtime repo 

`flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
`
it's working now.. you should know i was waiting for someone to make this flatpak since the deb packages was released so thanks
but i wanna ask how frequent you are updating it ?
i'll close the issue

**Comment by vrutkovs** [comment]
Its probably outdated flatpak package in F26, as it works in F27:
```
# flatpak --version
Flatpak 0.9.99
# flatpak install https://vrutkovs.github.io/flatpak-signal/signal.flatpakref
This application depends on runtimes from:
  https://flathub.org/repo/
Configure this as new remote 'flathub' [y/n]: y
Installing: org.signal.Desktop/x86_64/master
Required runtime for org.signal.Desktop/x86_64/master (org.freedesktop.Platform/x86_64/1.6) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
Installing: org.freedesktop.Platform/x86_64/1.6 from flathub
...
```

>but i wanna ask how frequent you are updating it ?

I'll try to keep it updated as often as possible (going to build 1.0.35 released now), but can't guarantee it

**Comment by ghost** [comment]
i have the same flatpak version 
`Flatpak 0.9.99
`
i really hope openwhisper adopts the flatpak packaging solution as it's working on almost every distro
